In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df=pd.read_csv("jobss.csv")

In [3]:
df.head()

,Job Title,Unnamed: 1,Job Experience Required,Key Skills,Role Category,Location,Functional Area,Industry,Role,Longitude,Latitude,sal
0,Digital Media Planner,NaN,5 - 10 yrs,Media Planning| Digital Media,Advertising,Mumbai,"Marketing , Advertising , MR , PR , Media Plan...","Advertising, PR, MR, Event Management",Media Planning Executive/Manager,72.877393,19.075990,3855
1,Online Bidding Executive,NaN,2 - 5 yrs,pre sales| closing| software knowledge| clien...,Retail Sales,"Pune,Pune","Sales , Retail , Business Development","IT-Software, Software Services",Sales Executive/Officer,73.854454,18.521428,2639
2,Trainee Research/ Research Executive- Hi- Tec...,NaN,0 - 1 yrs,Computer science| Fabrication| Quality check|...,R&D,Gurgaon,"Engineering Design , R&D","Recruitment, Staffing",R&D Executive,77.002700,28.428262,2156
3,Technical Support,NaN,0 - 5 yrs,Technical Support,Admin/Maintenance/Security/Datawarehousing,Mumbai,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Technical Support Engineer,72.877393,19.075990,4059
4,Software Test Engineer -hyderabad,NaN,2 - 5 yrs,manual testing| test engineering| test cases|...,Programming & Design,Hyderabad,IT Software - QA & Testing,"IT-Software, Software Services",Testing Engineer,78.474061,17.360589,5347

In [4]:
df.dtypes

Job Title                   object
Unnamed: 1                 float64
Job Experience Required     object
Key Skills                  object
Role Category               object
Location                    object
Functional Area             object
Industry                    object
Role                        object
Longitude                  float64
Latitude                   float64
sal                          int64
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Job Title                489 non-null    object
 1   Unnamed: 1               0 non-null      float64
 2   Job Experience Required  500 non-null    object
 3   Key Skills               500 non-null    object
 4   Role Category            463 non-null    object
 5   Location                 489 non-null    object
 6   Functional Area          489 non-null    object
 7   Industry                 489 non-null    object
 8   Role                     486 non-null    object
 9   Longitude                473 non-null    float64
 10  Latitude                 473 non-null    float64
 11  sal                      500 non-null    int64
dtypes: float64(3), int64(1), object(8)
memory usage: 47.0+ KB

In [6]:
df.duplicated().sum()

0

In [7]:
df.shape

(500, 12)

In [8]:
df.isna().sum()

Job Title                   11
Unnamed: 1                 500
Job Experience Required      0
Key Skills                   0
Role Category               37
Location                    11
Functional Area             11
Industry                    11
Role                        14
Longitude                   27
Latitude                    27
sal                          0
dtype: int64

In [9]:
import pandas as pd

# Load dataset
df = pd.read_csv('jobss.csv')

# Drop irrelevant columns
df = df.drop(columns=['Unnamed: 1'])

# Fill missing values in categorical columns with mode or 'Unknown'
for col in ['Job Title', 'Role Category', 'Location', 'Functional Area', 'Industry', 'Role']:
    if df[col].isna().sum() > 0:
        df[col].fillna(df[col].mode()[0], inplace=True)

# Fill missing longitude/latitude with median or drop rows
df['Longitude'].fillna(df['Longitude'].median(), inplace=True)
df['Latitude'].fillna(df['Latitude'].median(), inplace=True)

# Check if 'sal' column has missing; if so fill with median
if df['sal'].isna().sum() > 0:
    df['sal'].fillna(df['sal'].median(), inplace=True)

# Process Job Experience Required to extract numeric features
# Extract min and max years from string like "5 - 10 yrs"
def extract_years(exp_str):
    try:
        numbers = [int(s) for s in exp_str.split() if s.isdigit()]
        if len(numbers) == 2:
            return numbers[0], numbers[1]
        elif len(numbers) == 1:
            return numbers[0], numbers[0]
        else:
            return None, None
    except:
        return None, None

df['Min_Experience'], df['Max_Experience'] = zip(*df['Job Experience Required'].map(extract_years))

# For rows where extraction failed, fill with median or mode
median_min_exp = df['Min_Experience'].median()
median_max_exp = df['Max_Experience'].median()
df['Min_Experience'].fillna(median_min_exp, inplace=True)
df['Max_Experience'].fillna(median_max_exp, inplace=True)

# Optional: Split or process 'Key Skills' which are pipe-separated
# Convert to lowercase, strip spaces
df['Key Skills'] = df['Key Skills'].str.lower().str.strip()

C:\Users\USER\AppData\Local\Temp\ipykernel_19312\2932170615.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_19312\2932170615.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Longitude'].fillna(df['Longitude'].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_19312\2932170615.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Latitude'].fillna(df['Latitude'].median(), inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_19312\2932170615.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min_Experience'].fillna(median_min_exp, inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_19312\2932170615.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Max_Experience'].fillna(median_max_exp, inplace=True)

In [10]:
df.head()

,Job Title,Job Experience Required,Key Skills,Role Category,Location,Functional Area,Industry,Role,Longitude,Latitude,sal,Min_Experience,Max_Experience
0,Digital Media Planner,5 - 10 yrs,media planning| digital media,Advertising,Mumbai,"Marketing , Advertising , MR , PR , Media Plan...","Advertising, PR, MR, Event Management",Media Planning Executive/Manager,72.877393,19.075990,3855,5.0,10.0
1,Online Bidding Executive,2 - 5 yrs,pre sales| closing| software knowledge| client...,Retail Sales,"Pune,Pune","Sales , Retail , Business Development","IT-Software, Software Services",Sales Executive/Officer,73.854454,18.521428,2639,2.0,5.0
2,Trainee Research/ Research Executive- Hi- Tec...,0 - 1 yrs,computer science| fabrication| quality check| ...,R&D,Gurgaon,"Engineering Design , R&D","Recruitment, Staffing",R&D Executive,77.002700,28.428262,2156,0.0,1.0
3,Technical Support,0 - 5 yrs,technical support,Admin/Maintenance/Security/Datawarehousing,Mumbai,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Technical Support Engineer,72.877393,19.075990,4059,0.0,5.0
4,Software Test Engineer -hyderabad,2 - 5 yrs,manual testing| test engineering| test cases| ...,Programming & Design,Hyderabad,IT Software - QA & Testing,"IT-Software, Software Services",Testing Engineer,78.474061,17.360589,5347,2.0,5.0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Job Title                500 non-null    object
 1   Job Experience Required  500 non-null    object
 2   Key Skills               500 non-null    object
 3   Role Category            500 non-null    object
 4   Location                 500 non-null    object
 5   Functional Area          500 non-null    object
 6   Industry                 500 non-null    object
 7   Role                     500 non-null    object
 8   Longitude                500 non-null    float64
 9   Latitude                 500 non-null    float64
 10  sal                      500 non-null    int64
 11  Min_Experience           500 non-null    float64
 12  Max_Experience           500 non-null    float64
dtypes: float64(4), int64(1), object(8)
memory usage: 50.9+ KB

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
import numpy as np

# 1. TF-IDF vectorizer for Key Skills
# Replace '|' with spaces to treat skills as words
df['Key Skills'] = df['Key Skills'].str.replace('|', ' ')

tfidf = TfidfVectorizer(max_features=500, stop_words='english')
skills_tfidf = tfidf.fit_transform(df['Key Skills'])

# 2. Encode categorical columns
categorical_cols = ['Job Title', 'Role Category', 'Location', 'Functional Area', 'Industry', 'Role']

# Use LabelEncoder for simplicity
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = df[col].fillna('Unknown')
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# 3. Numeric features
numeric_features = df[['Min_Experience', 'Max_Experience', 'sal']].values

# 4. Combine all features
from scipy.sparse import hstack

X = hstack([skills_tfidf, numeric_features, df[categorical_cols].values])
y = df['Role']  

# X is sparse matrix; y is label vector
print('Feature matrix shape:', X.shape)
print('Target vector shape:', y.shape)

Feature matrix shape: (500, 509)
Target vector shape: (500,)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from scipy.sparse import hstack, csr_matrix
import numpy as np

# TF-IDF skills vector (main feature for resume screening)
tfidf = TfidfVectorizer(max_features=300, stop_words='english')
skills_tfidf = tfidf.fit_transform(df['Key Skills'])

# Numeric experience features
X_num = df[['Min_Experience', 'Max_Experience']].values

# Optional: Encode 'Job Title' if you believe it's predictive
le_title = LabelEncoder()
X_title = le_title.fit_transform(df['Job Title']).reshape(-1, 1)

# Stack features (ensure everything has the same number of rows)
X_sparse = hstack([
    skills_tfidf,                     # n_samples x n_tfidf_features
    csr_matrix(X_num),                # n_samples x 2
    csr_matrix(X_title)               # n_samples x 1
]).tocsr()

# Target variable
y = df['Role'].values

# Remove rare classes (as before) using one mask for all columns
from collections import Counter
class_counts = Counter(y)
rare_classes = [cls for cls, count in class_counts.items() if count < 2]
mask = ~np.isin(y, rare_classes)
X_sparse = X_sparse[mask]
y = y[mask]

# Now split and model as usual
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_sparse, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
import pandas as pd
from collections import Counter

# Assume df is your DataFrame and 'Role' is the target column

# Count class occurrences
role_counts = Counter(df['Role'])

# Define minimum samples threshold
min_samples = 10

# Function to map rare job roles to 'Other'
def group_rare_roles(role):
    if role_counts[role] < min_samples:
        return 'Other'
    else:
        return role

# Apply grouping
df['Role_grouped'] = df['Role'].apply(group_rare_roles)

# Check grouping results
print(df['Role_grouped'].value_counts())

# Now proceed with the rest of your processing, using 'Role_grouped' as the target column

# Continue with label encoding, feature engineering, model training on 'Role_grouped'

In [18]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from scipy.sparse import hstack, csr_matrix
from collections import Counter

# Load data
df = pd.read_csv('jobss.csv')

# Basic feature prep
df['Key Skills'] = df['Key Skills'].fillna("").str.lower().str.replace('|', ' ')
df['Min_Experience'], df['Max_Experience'] = zip(*df['Job Experience Required'].map(
    lambda x: ([int(s) for s in str(x).split() if s.isdigit()] + [0, 0])[:2]))
df['Role'] = df['Role'].fillna('Unknown')

# Group rare classes into 'Other'
role_counts = Counter(df['Role'])
min_samples = 10
df['Role_grouped'] = df['Role'].apply(lambda r: r if role_counts[r] >= min_samples else 'Other')

# TF-IDF vectorization
tfidf = TfidfVectorizer(max_features=100, stop_words='english')
skills_tfidf = tfidf.fit_transform(df['Key Skills'])

# Numeric experience
X_num = np.array(df[['Min_Experience', 'Max_Experience']])

# Features combined
X = hstack([skills_tfidf, csr_matrix(X_num)]).tocsr()

# Target label encoded
le = LabelEncoder()
y = le.fit_transform(df['Role_grouped'])

# Train/test split with stratify on grouped roles
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Models to try
models = {
    'Logistic Regression': LogisticRegression(max_iter=500),
    'Random Forest': RandomForestClassifier(n_estimators=100),
    'SVM': SVC()
}

# Train, evaluate, cross-validate
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(f'=== {name} ===')
    print(f'Accuracy: {accuracy_score(y_test, y_pred):.4f}')
    print(classification_report(y_test, y_pred, target_names=le.classes_))
    cv_scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')
    print(f'5-fold CV Accuracy: {cv_scores.mean():.4f} +/- {cv_scores.std():.4f}\n')

=== Logistic Regression ===
Accuracy: 0.6300
                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       0.00      0.00      0.00         3
Associate/Senior Associate -(NonTechnical)       0.50      0.29      0.36         7
   Associate/Senior Associate -(Technical)       0.00      0.00      0.00         2
                                     Other       0.63      0.93      0.75        54
                   Sales Executive/Officer       0.00      0.00      0.00         3
        Sales/Business Development Manager       1.00      0.14      0.25         7
                        Software Developer       0.69      0.47      0.56        19
                  Team Lead/Technical Lead       0.00      0.00      0.00         2
                                   Unknown       0.50      0.33      0.40         3

                                  accuracy                           0.63       100
                                 macro avg       0.37      0.24      0.26       100
                              weighted avg       0.59      0.63      0.57       100

C:\Users\sanju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sanju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sanju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

5-fold CV Accuracy: 0.6720 +/- 0.0407

=== Random Forest ===
Accuracy: 0.6400
                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       0.00      0.00      0.00         3
Associate/Senior Associate -(NonTechnical)       0.57      0.57      0.57         7
   Associate/Senior Associate -(Technical)       0.00      0.00      0.00         2
                                     Other       0.66      0.85      0.74        54
                   Sales Executive/Officer       0.00      0.00      0.00         3
        Sales/Business Development Manager       1.00      0.29      0.44         7
                        Software Developer       0.65      0.58      0.61        19
                  Team Lead/Technical Lead       0.00      0.00      0.00         2
                                   Unknown       0.50      0.33      0.40         3

                                  accuracy                           0.64       100
                                 macro avg       0.38      0.29      0.31       100
                              weighted avg       0.60      0.64      0.60       100

C:\Users\sanju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sanju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sanju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

5-fold CV Accuracy: 0.6520 +/- 0.0299

=== SVM ===
Accuracy: 0.5400
                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       0.00      0.00      0.00         3
Associate/Senior Associate -(NonTechnical)       0.00      0.00      0.00         7
   Associate/Senior Associate -(Technical)       0.00      0.00      0.00         2
                                     Other       0.54      1.00      0.70        54
                   Sales Executive/Officer       0.00      0.00      0.00         3
        Sales/Business Development Manager       0.00      0.00      0.00         7
                        Software Developer       0.00      0.00      0.00        19
                  Team Lead/Technical Lead       0.00      0.00      0.00         2
                                   Unknown       0.00      0.00      0.00         3

                                  accuracy                           0.54       100
                                 macro avg       0.06      0.11      0.08       100
                              weighted avg       0.29      0.54      0.38       100

5-fold CV Accuracy: 0.5420 +/- 0.0040

C:\Users\sanju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sanju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sanju\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [19]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

rf = RandomForestClassifier(random_state=42)

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,
    n_jobs=-1,
    scoring='accuracy',
    verbose=2
)

grid_search.fit(X_train, y_train)

print(f'Best RF Score: {grid_search.best_score_:.4f}')
print(f'Best Params: {grid_search.best_params_}')

# Evaluate on test set using best estimator
best_rf = grid_search.best_estimator_
y_pred = best_rf.predict(X_test)

print(f'Test Accuracy: {accuracy_score(y_test, y_pred):.4f}')
print(classification_report(y_test, y_pred, target_names=le.classes_))

Fitting 3 folds for each of 108 candidates, totalling 324 fits
Best RF Score: 0.7101
Best Params: {'max_depth': 20, 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 200}
Test Accuracy: 0.6500
                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       0.00      0.00      0.00         3
Associate/Senior Associate -(NonTechnical)       0.60      0.43      0.50         7
   Associate/Senior Associate -(Technical)       0.00      0.00      0.00         2
                                     Other       0.65      0.89      0.75        54
                   Sales Executive/Officer       0.00      0.00      0.00         3
        Sales/Business Development Manager       0.67      0.29      0.40         7
                        Software Developer       0.69      0.58      0.63        19
                  Team Lead/Technical Lead       0.00      0.00      0.00         2
                                   Unknown       0.50      0.33      0.40         3

                                  accuracy                           0.65       100
                                 macro avg       0.34      0.28      0.30       100
                              weighted avg       0.58      0.65      0.60       100

C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
pip install transformers

In [ ]:
pip install torch

In [20]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# Define parameter grids
param_grid_lr = {
    'C': [0.01, 0.1, 1, 10],
    'penalty': ['l2'],
    'solver': ['lbfgs']
}

param_grid_rf = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

param_grid_svm = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}

# Initialize models
lr = LogisticRegression(max_iter=1000)
rf = RandomForestClassifier(random_state=42)
svm = SVC(probability=True)

# GridSearchCV objects
grid_lr = GridSearchCV(lr, param_grid_lr, cv=3, scoring='accuracy', n_jobs=-1, verbose=2)
grid_rf = GridSearchCV(rf, param_grid_rf, cv=3, scoring='accuracy', n_jobs=-1, verbose=2)
grid_svm = GridSearchCV(svm, param_grid_svm, cv=3, scoring='accuracy', n_jobs=-1, verbose=2)

# Fit models on training data X_train, y_train
grid_lr.fit(X_train, y_train)
print(f'Best Logistic Regression params: {grid_lr.best_params_}')
print(f'Best Logistic Regression score: {grid_lr.best_score_:.4f}')

grid_rf.fit(X_train, y_train)
print(f'Best Random Forest params: {grid_rf.best_params_}')
print(f'Best Random Forest score: {grid_rf.best_score_:.4f}')

grid_svm.fit(X_train, y_train)
print(f'Best SVM params: {grid_svm.best_params_}')
print(f'Best SVM score: {grid_svm.best_score_:.4f}')

# Evaluate best models on test data
models_best = {
    'Logistic Regression': grid_lr.best_estimator_,
    'Random Forest': grid_rf.best_estimator_,
    'SVM': grid_svm.best_estimator_
}

from sklearn.metrics import classification_report, accuracy_score

for name, model in models_best.items():
    y_pred = model.predict(X_test)
    print(f'=== {name} Test Results ===')
    print(f'Accuracy: {accuracy_score(y_test, y_pred):.4f}')
    print(classification_report(y_test, y_pred, target_names=le.classes_))

Fitting 3 folds for each of 4 candidates, totalling 12 fits
Best Logistic Regression params: {'C': 1, 'penalty': 'l2', 'solver': 'lbfgs'}
Best Logistic Regression score: 0.6900
Fitting 3 folds for each of 81 candidates, totalling 243 fits
Best Random Forest params: {'max_depth': 20, 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 200}
Best Random Forest score: 0.7101
Fitting 3 folds for each of 12 candidates, totalling 36 fits
Best SVM params: {'C': 1, 'gamma': 'scale', 'kernel': 'linear'}
Best SVM score: 0.7125
=== Logistic Regression Test Results ===
Accuracy: 0.6200
                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       0.00      0.00      0.00         3
Associate/Senior Associate -(NonTechnical)       0.50      0.29      0.36         7
   Associate/Senior Associate -(Technical)       0.00      0.00      0.00         2
                                     Other       0.63      0.91      0.74        54
                   Sales Executive/Officer       0.00      0.00      0.00         3
        Sales/Business Development Manager       1.00      0.14      0.25         7
                        Software Developer       0.64      0.47      0.55        19
                  Team Lead/Technical Lead       0.00      0.00      0.00         2
                                   Unknown       0.50      0.33      0.40         3

                                  accuracy                           0.62       100
                                 macro avg       0.36      0.24      0.26       100
                              weighted avg       0.58      0.62      0.56       100

=== Random Forest Test Results ===
Accuracy: 0.6500
                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       0.00      0.00      0.00         3
Associate/Senior Associate -(NonTechnical)       0.60      0.43      0.50         7
   Associate/Senior Associate -(Technical)       0.00      0.00      0.00         2
                                     Other       0.65      0.89      0.75        54
                   Sales Executive/Officer       0.00      0.00      0.00         3
        Sales/Business Development Manager       0.67      0.29      0.40         7
                        Software Developer       0.69      0.58      0.63        19
                  Team Lead/Technical Lead       0.00      0.00      0.00         2
                                   Unknown       0.50      0.33      0.40         3

                                  accuracy                           0.65       100
                                 macro avg       0.34      0.28      0.30       100
                              weighted avg       0.58      0.65      0.60       100

=== SVM Test Results ===
Accuracy: 0.6500
                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       0.00      0.00      0.00         3
Associate/Senior Associate -(NonTechnical)       0.60      0.43      0.50         7
   Associate/Senior Associate -(Technical)       0.00      0.00      0.00         2
                                     Other       0.65      0.93      0.76        54
                   Sales Executive/Officer       0.00      0.00      0.00         3
        Sales/Business Development Manager       0.00      0.00      0.00         7
                        Software Developer       0.73      0.58      0.65        19
                  Team Lead/Technical Lead       0.00      0.00      0.00         2
                                   Unknown       0.50      0.33      0.40         3

                                  accuracy                           0.65       100
                                 macro avg       0.28      0.25      0.26       100
                              weighted avg       0.55      0.65      0.58       100

C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [23]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, accuracy_score

# Initialize XGBoost classifier
xgb = XGBClassifier(eval_metric='mlogloss', use_label_encoder=False)

# Parameter grid for tuning
param_grid_xgb = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 6, 10],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.7, 1.0],
    'colsample_bytree': [0.7, 1.0]
}

# GridSearchCV object
grid_xgb = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid_xgb,
    cv=3,
    scoring='accuracy',
    n_jobs=-1,
    verbose=2
)

# Fit GridSearchCV on training data
grid_xgb.fit(X_train, y_train)

# Print best score and params
print(f'Best XGB Score: {grid_xgb.best_score_:.4f}')
print(f'Best XGB Params: {grid_xgb.best_params_}')

# Evaluate on test set
best_xgb = grid_xgb.best_estimator_
y_pred = best_xgb.predict(X_test)

print(f'XGB Test Accuracy: {accuracy_score(y_test, y_pred):.4f}')
print(classification_report(y_test, y_pred, target_names=le.classes_))

Fitting 3 folds for each of 108 candidates, totalling 324 fits

C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\xgboost\core.py:158: UserWarning: [19:48:06] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-08cbc0333d8d4aae1-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

Best XGB Score: 0.6776
Best XGB Params: {'colsample_bytree': 1.0, 'learning_rate': 0.01, 'max_depth': 10, 'n_estimators': 200, 'subsample': 0.7}
XGB Test Accuracy: 0.6300
                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       0.00      0.00      0.00         3
Associate/Senior Associate -(NonTechnical)       0.50      0.29      0.36         7
   Associate/Senior Associate -(Technical)       0.00      0.00      0.00         2
                                     Other       0.63      0.89      0.74        54
                   Sales Executive/Officer       0.00      0.00      0.00         3
        Sales/Business Development Manager       0.60      0.43      0.50         7
                        Software Developer       0.69      0.47      0.56        19
                  Team Lead/Technical Lead       0.00      0.00      0.00         2
                                   Unknown       0.50      0.33      0.40         3

                                  accuracy                           0.63       100
                                 macro avg       0.32      0.27      0.28       100
                              weighted avg       0.56      0.63      0.58       100

C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
import transformers

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())  # Should print True if CUDA GPU is available

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_bert = BertModel.from_pretrained('bert-base-uncased').to(device)

# In encoding function, send batch tensors to device:
encoded_input = tokenizer(batch.tolist(), padding=True, truncation=True, return_tensors='pt').to(device)
with torch.no_grad():
    output = model_bert(**encoded_input)

In [25]:
pip install transformers

Defaulting to user installation because normal site-packages is not writeable
Collecting transformers
  Downloading transformers-4.56.2-py3-none-any.whl (11.6 MB)
     ---------------------------------------- 11.6/11.6 MB 5.3 MB/s eta 0:00:00
Requirement already satisfied: regex!=2019.12.17 in c:\programdata\anaconda3\lib\site-packages (from transformers) (2022.7.9)
Requirement already satisfied: numpy>=1.17 in c:\users\user\appdata\roaming\python\python39\site-packages (from transformers) (1.22.4)
Requirement already satisfied: pyyaml>=5.1 in c:\programdata\anaconda3\lib\site-packages (from transformers) (6.0)
Collecting tokenizers<=0.23.0,>=0.22.0
  Downloading tokenizers-0.22.1-cp39-abi3-win_amd64.whl (2.7 MB)
     ---------------------------------------- 2.7/2.7 MB 7.1 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from transformers) (21.3)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from transformers) (2.28.1)
Collecting huggingface-hub<1.0,>=0.34.0
  Downloading huggingface_hub-0.35.0-py3-none-any.whl (563 kB)
     -------------------------------------- 563.4/563.4 kB 8.9 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.27 in c:\programdata\anaconda3\lib\site-packages (from transformers) (4.64.1)
Collecting safetensors>=0.4.3
  Downloading safetensors-0.6.2-cp38-abi3-win_amd64.whl (320 kB)
     -------------------------------------- 320.2/320.2 kB 6.6 MB/s eta 0:00:00
Requirement already satisfied: filelock in c:\programdata\anaconda3\lib\site-packages (from transformers) (3.6.0)
Collecting fsspec>=2023.5.0
  Downloading fsspec-2025.9.0-py3-none-any.whl (199 kB)
     -------------------------------------- 199.3/199.3 kB 6.1 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\user\appdata\roaming\python\python39\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\programdata\anaconda3\lib\site-packages (from packaging>=20.0->transformers) (3.0.9)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\roaming\python\python39\site-packages (from requests->transformers) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->transformers) (1.26.11)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->transformers) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->transformers) (2022.9.14)
Installing collected packages: safetensors, fsspec, huggingface-hub, tokenizers, transformers
Successfully installed fsspec-2025.9.0 huggingface-hub-0.35.0 safetensors-0.6.2 tokenizers-0.22.1 transformers-4.56.2
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts hf.exe, huggingface-cli.exe and tiny-agents.exe are installed in 'C:\Users\USER\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts transformers-cli.exe and transformers.exe are installed in 'C:\Users\USER\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [22]:
pip install xgboost

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Collecting xgboost
  Downloading xgboost-2.1.4-py3-none-win_amd64.whl (124.9 MB)
     ------------------------------------ 124.9/124.9 MB 622.5 kB/s eta 0:00:00
Requirement already satisfied: scipy in c:\users\user\appdata\roaming\python\python39\site-packages (from xgboost) (1.8.1)
Requirement already satisfied: numpy in c:\users\user\appdata\roaming\python\python39\site-packages (from xgboost) (1.22.4)
Installing collected packages: xgboost
Successfully installed xgboost-2.1.4

In [26]:
pip install torch

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

  WARNING: The script isympy.exe is installed in 'C:\Users\USER\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts torchfrtrace.exe and torchrun.exe are installed in 'C:\Users\USER\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

Collecting torch
  Downloading torch-2.8.0-cp39-cp39-win_amd64.whl (241.2 MB)
     ------------------------------------ 241.2/241.2 MB 845.4 kB/s eta 0:00:00
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from torch) (2.11.3)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\user\appdata\roaming\python\python39\site-packages (from torch) (4.15.0)
Collecting sympy>=1.13.3
  Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
     ---------------------------------------- 6.3/6.3 MB 6.0 MB/s eta 0:00:00
Requirement already satisfied: networkx in c:\programdata\anaconda3\lib\site-packages (from torch) (2.8.4)
Requirement already satisfied: fsspec in c:\users\user\appdata\roaming\python\python39\site-packages (from torch) (2025.9.0)
Requirement already satisfied: filelock in c:\programdata\anaconda3\lib\site-packages (from torch) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.2.1)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\anaconda3\lib\site-packages (from jinja2->torch) (2.0.1)
Installing collected packages: sympy, torch
Successfully installed sympy-1.14.0 torch-2.8.0

In [27]:
from transformers import BertTokenizer, BertModel
import torch
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score
from scipy.sparse import csr_matrix, hstack
from collections import Counter

# Load data
df = pd.read_csv('jobss.csv')
df['Key Skills'] = df['Key Skills'].fillna("").str.lower().str.replace('|', ' ')
df['Min_Experience'], df['Max_Experience'] = zip(*df['Job Experience Required'].map(
    lambda x: ([int(s) for s in str(x).split() if s.isdigit()] + [0,0])[:2]))
df['Role'] = df['Role'].fillna('Unknown')

# Group rare classes
role_counts = df['Role'].value_counts()
min_samples = 10
df['Role_grouped'] = df['Role'].apply(lambda r: r if role_counts[r] >= min_samples else 'Other')

# BERT setup
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model_bert = BertModel.from_pretrained('bert-base-uncased')

def bert_encode(texts, batch_size=16):
    embeddings = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]
        encoded_input = tokenizer(batch.tolist(), padding=True, truncation=True, return_tensors='pt')
        with torch.no_grad():
            output = model_bert(**encoded_input)
        cls_embeddings = output.last_hidden_state[:, 0, :].numpy()
        embeddings.append(cls_embeddings)
    return np.vstack(embeddings)

skills_embeddings = bert_encode(df['Key Skills'])

# Combine BERT embeddings with numeric features
X_num = df[['Min_Experience', 'Max_Experience']].values
X = np.hstack((skills_embeddings, X_num))

# Encode labels
le = LabelEncoder()
y = le.fit_transform(df['Role_grouped'])

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Parameter grids for tuning
param_grid_lr = {'C': [0.01, 0.1, 1, 10], 'penalty': ['l2'], 'solver': ['lbfgs']}
param_grid_rf = {'n_estimators': [100, 200], 'max_depth': [None, 20], 'min_samples_split': [2,5], 'min_samples_leaf': [1,2]}
param_grid_svm = {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf'], 'gamma': ['scale', 'auto']}
param_grid_xgb = {'n_estimators': [100, 200], 'max_depth': [3,6], 'learning_rate':[0.01, 0.1], 'subsample':[0.7,1.0], 'colsample_bytree':[0.7, 1.0]}

# Initialize models
lr = LogisticRegression(max_iter=1000)
rf = RandomForestClassifier(random_state=42)
svm = SVC(probability=True)
xgb = XGBClassifier(eval_metric='mlogloss', use_label_encoder=False)

# GridSearchCV setup
grid_lr = GridSearchCV(lr, param_grid_lr, cv=3, scoring='accuracy', n_jobs=-1, verbose=2)
grid_rf = GridSearchCV(rf, param_grid_rf, cv=3, scoring='accuracy', n_jobs=-1, verbose=2)
grid_svm = GridSearchCV(svm, param_grid_svm, cv=3, scoring='accuracy', n_jobs=-1, verbose=2)
grid_xgb = GridSearchCV(xgb, param_grid_xgb, cv=3, scoring='accuracy', n_jobs=-1, verbose=2)

# Fit models
grid_lr.fit(X_train, y_train)
grid_rf.fit(X_train, y_train)
grid_svm.fit(X_train, y_train)
grid_xgb.fit(X_train, y_train)

# Print best params and scores
print(f'Best Logistic Regression params: {grid_lr.best_params_}, score: {grid_lr.best_score_:.4f}')
print(f'Best Random Forest params: {grid_rf.best_params_}, score: {grid_rf.best_score_:.4f}')
print(f'Best SVM params: {grid_svm.best_params_}, score: {grid_svm.best_score_:.4f}')
print(f'Best XGB params: {grid_xgb.best_params_}, score: {grid_xgb.best_score_:.4f}')

# Evaluate on test set
models_best = {
    'Logistic Regression': grid_lr.best_estimator_,
    'Random Forest': grid_rf.best_estimator_,
    'SVM': grid_svm.best_estimator_,
    'XGBoost': grid_xgb.best_estimator_
}

for name, model in models_best.items():
    y_pred = model.predict(X_test)
    print(f'=== {name} Test Results ===')
    print(f'Accuracy: {accuracy_score(y_test, y_pred):.4f}')
    print(classification_report(y_test, y_pred, target_names=le.classes_))

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\USER\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Fitting 3 folds for each of 4 candidates, totalling 12 fits
Fitting 3 folds for each of 16 candidates, totalling 48 fits
Fitting 3 folds for each of 12 candidates, totalling 36 fits
Fitting 3 folds for each of 32 candidates, totalling 96 fits

C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\xgboost\core.py:158: UserWarning: [20:14:01] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-08cbc0333d8d4aae1-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

Best Logistic Regression params: {'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}, score: 0.6725
Best Random Forest params: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 200}, score: 0.6475
Best SVM params: {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}, score: 0.6950
Best XGB params: {'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200, 'subsample': 0.7}, score: 0.6900
=== Logistic Regression Test Results ===
Accuracy: 0.6400
                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       0.00      0.00      0.00         3
Associate/Senior Associate -(NonTechnical)       0.67      0.29      0.40         7
   Associate/Senior Associate -(Technical)       0.00      0.00      0.00         2
                                     Other       0.63      0.91      0.74        54
                   Sales Executive/Officer       0.00      0.00      0.00         3
        Sales/Business Development Manager       1.00      0.29      0.44         7
                        Software Developer       0.62      0.53      0.57        19
                  Team Lead/Technical Lead       0.00      0.00      0.00         2
                                   Unknown       1.00      0.33      0.50         3

                                  accuracy                           0.64       100
                                 macro avg       0.44      0.26      0.30       100
                              weighted avg       0.60      0.64      0.58       100

=== Random Forest Test Results ===
Accuracy: 0.6200
                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       0.00      0.00      0.00         3
Associate/Senior Associate -(NonTechnical)       0.00      0.00      0.00         7
   Associate/Senior Associate -(Technical)       0.00      0.00      0.00         2
                                     Other       0.61      0.94      0.74        54
                   Sales Executive/Officer       0.00      0.00      0.00         3
        Sales/Business Development Manager       0.00      0.00      0.00         7
                        Software Developer       0.67      0.53      0.59        19
                  Team Lead/Technical Lead       0.00      0.00      0.00         2
                                   Unknown       1.00      0.33      0.50         3

                                  accuracy                           0.62       100
                                 macro avg       0.25      0.20      0.20       100
                              weighted avg       0.48      0.62      0.53       100

=== SVM Test Results ===
Accuracy: 0.6900

C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       0.00      0.00      0.00         3
Associate/Senior Associate -(NonTechnical)       0.60      0.43      0.50         7
   Associate/Senior Associate -(Technical)       0.00      0.00      0.00         2
                                     Other       0.69      0.93      0.79        54
                   Sales Executive/Officer       0.00      0.00      0.00         3
        Sales/Business Development Manager       1.00      0.14      0.25         7
                        Software Developer       0.70      0.74      0.72        19
                  Team Lead/Technical Lead       0.00      0.00      0.00         2
                                   Unknown       1.00      0.33      0.50         3

                                  accuracy                           0.69       100
                                 macro avg       0.44      0.29      0.31       100
                              weighted avg       0.65      0.69      0.63       100

=== XGBoost Test Results ===
Accuracy: 0.6500
                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       0.00      0.00      0.00         3
Associate/Senior Associate -(NonTechnical)       0.75      0.43      0.55         7
   Associate/Senior Associate -(Technical)       0.00      0.00      0.00         2
                                     Other       0.65      0.91      0.76        54
                   Sales Executive/Officer       0.00      0.00      0.00         3
        Sales/Business Development Manager       0.33      0.14      0.20         7
                        Software Developer       0.65      0.58      0.61        19
                  Team Lead/Technical Lead       0.00      0.00      0.00         2
                                   Unknown       1.00      0.33      0.50         3

                                  accuracy                           0.65       100
                                 macro avg       0.38      0.27      0.29       100
                              weighted avg       0.58      0.65      0.59       100

C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [6]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical

# Load data
df = pd.read_csv('jobss.csv')

# Preprocess text
df['Key Skills'] = df['Key Skills'].fillna("").str.lower().str.replace('|', ' ')

# Parse experience feature
df['Min_Experience'], df['Max_Experience'] = zip(*df['Job Experience Required'].map(
    lambda x: ([int(s) for s in str(x).split() if s.isdigit()] + [0,0])[:2]))
df['Role'] = df['Role'].fillna('Unknown')

# Group rare roles
role_counts = df['Role'].value_counts()
min_samples = 10
df['Role_grouped'] = df['Role'].apply(lambda r: r if role_counts[r] >= min_samples else 'Other')

# TF-IDF vectorization on skills
tfidf = TfidfVectorizer(max_features=200, stop_words='english')
skills_tfidf = tfidf.fit_transform(df['Key Skills'])

# Numeric features as array
X_num = df[['Min_Experience', 'Max_Experience']].values

# Combine sparse TF-IDF matrix and numeric features
from scipy.sparse import hstack, csr_matrix
X = hstack([skills_tfidf, csr_matrix(X_num)]).toarray()

# Encode labels
le = LabelEncoder()
y = le.fit_transform(df['Role_grouped'])
y_cat = to_categorical(y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_cat, test_size=0.2, random_state=42, stratify=y
)

# Define Keras model
model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(y_cat.shape[1], activation='softmax')
])

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train model
model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.1,
    verbose=2
)

# Evaluate model
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f'Test Accuracy: {accuracy:.4f}')

# Generate classification report
from sklearn.metrics import classification_report
import numpy as np

y_pred_prob = model.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)
y_true = np.argmax(y_test, axis=1)

print(classification_report(y_true, y_pred, target_names=le.classes_))

C:\Users\sanju\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/30
12/12 - 5s - 378ms/step - accuracy: 0.4500 - loss: 1.7177 - val_accuracy: 0.5500 - val_loss: 1.6332
Epoch 2/30
12/12 - 1s - 57ms/step - accuracy: 0.5361 - loss: 1.4756 - val_accuracy: 0.5500 - val_loss: 1.5593
Epoch 3/30
12/12 - 1s - 55ms/step - accuracy: 0.5306 - loss: 1.4149 - val_accuracy: 0.5500 - val_loss: 1.5080
Epoch 4/30
12/12 - 1s - 62ms/step - accuracy: 0.5389 - loss: 1.3749 - val_accuracy: 0.5500 - val_loss: 1.4562
Epoch 5/30
12/12 - 1s - 47ms/step - accuracy: 0.5611 - loss: 1.2766 - val_accuracy: 0.6000 - val_loss: 1.4166
Epoch 6/30
12/12 - 0s - 30ms/step - accuracy: 0.5806 - loss: 1.2271 - val_accuracy: 0.6000 - val_loss: 1.3750
Epoch 7/30
12/12 - 1s - 56ms/step - accuracy: 0.6111 - loss: 1.1732 - val_accuracy: 0.6500 - val_loss: 1.3322
Epoch 8/30
12/12 - 1s - 59ms/step - accuracy: 0.6722 - loss: 1.0737 - val_accuracy: 0.7250 - val_loss: 1.2485
Epoch 9/30
12/12 - 1s - 51ms/step - accuracy: 0.7056 - loss: 1.0247 - val_accuracy: 0.7250 - val_loss: 1.1746
Epoch 10/30
12/12 - 1s - 56ms/step - accuracy: 0.7250 - loss: 0.9522 - val_accuracy: 0.7250 - val_loss: 1.1834
Epoch 11/30
12/12 - 1s - 55ms/step - accuracy: 0.7306 - loss: 0.8856 - val_accuracy: 0.7000 - val_loss: 1.1645
Epoch 12/30
12/12 - 0s - 30ms/step - accuracy: 0.7250 - loss: 0.8574 - val_accuracy: 0.7250 - val_loss: 1.0937
Epoch 13/30
12/12 - 0s - 30ms/step - accuracy: 0.7361 - loss: 0.7624 - val_accuracy: 0.7000 - val_loss: 1.1299
Epoch 14/30
12/12 - 1s - 53ms/step - accuracy: 0.7389 - loss: 0.7396 - val_accuracy: 0.6750 - val_loss: 1.1324
Epoch 15/30
12/12 - 0s - 28ms/step - accuracy: 0.7611 - loss: 0.7071 - val_accuracy: 0.7000 - val_loss: 1.0972
Epoch 16/30
12/12 - 1s - 54ms/step - accuracy: 0.7806 - loss: 0.6458 - val_accuracy: 0.7000 - val_loss: 1.1476
Epoch 17/30
12/12 - 0s - 29ms/step - accuracy: 0.7722 - loss: 0.6100 - val_accuracy: 0.6500 - val_loss: 1.1348
Epoch 18/30
12/12 - 0s - 31ms/step - accuracy: 0.7944 - loss: 0.5692 - val_accuracy: 0.6750 - val_loss: 1.1355
Epoch 19/30
12/12 - 1s - 52ms/step - accuracy: 0.8278 - loss: 0.5637 - val_accuracy: 0.6750 - val_loss: 1.1539
Epoch 20/30
12/12 - 0s - 28ms/step - accuracy: 0.8306 - loss: 0.4728 - val_accuracy: 0.7000 - val_loss: 1.1881
Epoch 21/30
12/12 - 0s - 26ms/step - accuracy: 0.8417 - loss: 0.4969 - val_accuracy: 0.7000 - val_loss: 1.1908
Epoch 22/30
12/12 - 0s - 30ms/step - accuracy: 0.8333 - loss: 0.4516 - val_accuracy: 0.6750 - val_loss: 1.2795
Epoch 23/30
12/12 - 1s - 58ms/step - accuracy: 0.8389 - loss: 0.4805 - val_accuracy: 0.7500 - val_loss: 1.2470
Epoch 24/30
12/12 - 1s - 47ms/step - accuracy: 0.8583 - loss: 0.4060 - val_accuracy: 0.7000 - val_loss: 1.2240
Epoch 25/30
12/12 - 0s - 28ms/step - accuracy: 0.8639 - loss: 0.3900 - val_accuracy: 0.7000 - val_loss: 1.2627
Epoch 26/30
12/12 - 0s - 34ms/step - accuracy: 0.8778 - loss: 0.3817 - val_accuracy: 0.7500 - val_loss: 1.2771
Epoch 27/30
12/12 - 0s - 28ms/step - accuracy: 0.8972 - loss: 0.3536 - val_accuracy: 0.7000 - val_loss: 1.2649
Epoch 28/30
12/12 - 1s - 55ms/step - accuracy: 0.9000 - loss: 0.3271 - val_accuracy: 0.7000 - val_loss: 1.3174
Epoch 29/30
12/12 - 1s - 53ms/step - accuracy: 0.9111 - loss: 0.2817 - val_accuracy: 0.7000 - val_loss: 1.3437
Epoch 30/30
12/12 - 1s - 53ms/step - accuracy: 0.9139 - loss: 0.2959 - val_accuracy: 0.7000 - val_loss: 1.3654
Test Accuracy: 0.6200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       0.00      0.00      0.00         3
Associate/Senior Associate -(NonTechnical)       0.40      0.29      0.33         7
   Associate/Senior Associate -(Technical)       0.00      0.00      0.00         2
                                     Other       0.66      0.89      0.76        54
                   Sales Executive/Officer       0.00      0.00      0.00         3
        Sales/Business Development Manager       1.00      0.14      0.25         7
                        Software Developer       0.67      0.53      0.59        19
                  Team Lead/Technical Lead       0.00      0.00      0.00         2
                                   Unknown       1.00      0.33      0.50         3

                                  accuracy                           0.62       100
                                 macro avg       0.41      0.24      0.27       100
                              weighted avg       0.61      0.62      0.58       100

In [8]:
import joblib

# Replace these with your variable names from your notebook
trained_model = model  # e.g., your final trained classifier or pipeline
label_encoder = le     # your sklearn LabelEncoder for roles
tfidf_vectorizer = tfidf  # your TF-IDF vectorizer on skills

# Save the objects for Flask app usage
joblib.dump(trained_model, 'model.pkl')
joblib.dump(label_encoder, 'label_encoder.pkl')
joblib.dump(tfidf_vectorizer, 'tfidf_vectorizer.pkl')

['tfidf_vectorizer.pkl']

In [9]:
import joblib
tfidf = joblib.load('tfidf_vectorizer.pkl')

In [10]:
pip install streamlit

Requirement already satisfied: streamlit in c:\users\sanju\anaconda3\lib\site-packages (1.45.1)
Requirement already satisfied: altair<6,>=4.0 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (8.1.8)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (2.2.6)
Requirement already satisfied: packaging<25,>=20 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<12,>=7.1.0 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (11.1.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (19.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (4.14.1)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\sanju\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\sanju\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\sanju\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\sanju\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (1.31.0)
Requirement already satisfied: colorama in c:\users\sanju\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\sanju\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\sanju\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sanju\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sanju\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sanju\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sanju\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sanju\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sanju\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sanju\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.8.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\sanju\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\sanju\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\sanju\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\sanju\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)
Requirement already satisfied: six>=1.5 in c:\users\sanju\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sanju\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [24]:
eval_df = pd.read_csv("model_evaluation_results.csv")

In [25]:
eval_df

,Model,Accuracy,Precision (macro avg),Recall (macro avg),F1-Score (macro avg)
0,Logistic Regression,0.66,0.495972,0.295136,0.341666
1,Random Forest,0.65,0.347299,0.275705,0.295545
2,SVM,0.66,0.337229,0.267737,0.283583
3,XGBoost,0.60,0.292582,0.220180,0.234059

In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

rf = RandomForestClassifier(random_state=42)
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

gridrf = GridSearchCV(estimator=rf, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1, verbose=2)
gridrf.fit(X_train, y_train)

best_rf = gridrf.best_estimator_

Fitting 3 folds for each of 81 candidates, totalling 243 fits

In [30]:
import joblib

# Save TF-IDF vectorizer
joblib.dump(tfidf, 'tfidf_vectorizer.pkl')
from flask import Flask, request, jsonify
import joblib
import numpy as np
from scipy.sparse import hstack, csr_matrix

# Load trained artifacts
rf_loaded = joblib.load('random_forest_model.pkl')
tfidf_loaded = joblib.load('tfidf_vectorizer.pkl')
le_loaded = joblib.load('label_encoder.pkl')

app = Flask(__name__)

@app.route('/predict', methods=['POST'])
def predict():
    # Expecting JSON with keys: skills, min_exp, max_exp, salary
    data = request.json
    skills = data.get('skills', '')
    min_exp = float(data.get('min_exp', 0))
    max_exp = float(data.get('max_exp', 0))
    salary = float(data.get('salary', 0))
    
    # Feature transformation
    skills_tfidf = tfidf_loaded.transform([skills])
    numeric_features = np.array([[min_exp, max_exp, salary]])
    numeric_sparse = csr_matrix(numeric_features)
    X_new = hstack([skills_tfidf, numeric_sparse])
    
    pred_encoded = rf_loaded.predict(X_new)
    pred_label = le_loaded.inverse_transform(pred_encoded)
    
    return jsonify({'predicted_role': str(pred_label[0])})

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)

# Save Label Encoder
joblib.dump(le, 'label_encoder.pkl')

# Save the best Random Forest model
joblib.dump(best_rf, 'random_forest_model.pkl')

['random_forest_model.pkl']

In [33]:
print(skills_tfidf.shape)  # Should be (1, N), where N is the training TF-IDF feature count

(1, 200)

In [34]:
print(numeric_features.shape)  # E.g. (1, 3) for (min_exp, max_exp, salary)

(1, 3)

In [35]:
print(X_new.shape)  # Must be (1, 1323). If not, you must match this

(1, 203)

In [39]:
import joblib
import numpy as np
from scipy.sparse import hstack, csr_matrix

# Load models and vectorizers
tfidf_loaded = joblib.load('tfidf_vectorizer.pkl')
le_loaded = joblib.load('label_encoder.pkl')
rf_loaded = joblib.load('random_forest_model.pkl')

# Input sample (modify for prediction)
new_skills = ["pre sales|software knowledge|clients"]     # Text input

# ---- Update these values & order to match training ----
min_exp = 2.0
max_exp = 5.0
salary = 50000
# Add more numeric features if required to reach full feature count (dummy example)
extra_features = [0.0]*(1323 - tfidf_loaded.transform(new_skills).shape[1] - 3)

numeric_features = np.array([[min_exp, max_exp, salary] + extra_features])
numeric_features_sparse = csr_matrix(numeric_features)

skills_tfidf = tfidf_loaded.transform(new_skills)

X_new = hstack([skills_tfidf, numeric_features_sparse])
print("Feature vector shape:", X_new.shape)  # Must be (1, 1323)

# Predict only if shape matches
if X_new.shape[1] == rf_loaded.n_features_in_:
    pred_encoded = rf_loaded.predict(X_new)
    pred_label = le_loaded.inverse_transform(pred_encoded)
    print("Predicted Job Role:", pred_label[0])
else:
    print(f"Feature mismatch: input has {X_new.shape[1]} features, but model expects {rf_loaded.n_features_in_}. Double-check feature engineering.")

Feature vector shape: (1, 1323)
Predicted Job Role: Unknown

In [42]:
print(le_loaded.classes_)

['Accounts Executive/Accountant'
 'Associate/Senior Associate -(NonTechnical)'
 'Associate/Senior Associate -(Technical)' 'Other'
 'Sales Executive/Officer' 'Sales/Business Development Manager'
 'Software Developer' 'Team Lead/Technical Lead' 'Unknown']

In [43]:
print("Encoded prediction:", pred_encoded)
print("Decoded job role:", pred_label)

Encoded prediction: [8]
Decoded job role: ['Unknown']

In [45]:
import pandas as pd
df = pd.read_csv('jobss.csv')
print(df['Role'].value_counts())

Role
Software Developer                            96
Sales/Business Development Manager            35
Associate/Senior Associate -(NonTechnical)    33
Other                                         20
Sales Executive/Officer                       16
                                              ..
Pre Sales Consultant                           1
Equity Manager                                 1
Telesales/Telemarketing Executive/Officer      1
Draughtsman                                    1
Pay Roll/Compensation Manager                  1
Name: count, Length: 138, dtype: int64

In [46]:
import pandas as pd

df = pd.read_csv('jobss.csv')
role_counts = df['Role'].value_counts()

# Set threshold: any role with less than X samples gets grouped as 'Other'
min_samples_for_role = 10
common_roles = role_counts[role_counts >= min_samples_for_role].index

df['Rolegrouped'] = df['Role'].apply(lambda x: x if x in common_roles else 'Other')
print(df['Rolegrouped'].value_counts())

Rolegrouped
Other                                         285
Software Developer                             96
Sales/Business Development Manager             35
Associate/Senior Associate -(NonTechnical)     33
Sales Executive/Officer                        16
Accounts Executive/Accountant                  14
Associate/Senior Associate -(Technical)        11
Team Lead/Technical Lead                       10
Name: count, dtype: int64

In [47]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE  # For oversampling rare classes
from scipy.sparse import hstack, csr_matrix
import joblib

# Load data
df = pd.read_csv('jobss.csv')

# Group roles with less than threshold samples as 'Other'
min_samples_for_role = 10
role_counts = df['Role'].value_counts()
common_roles = role_counts[role_counts >= min_samples_for_role].index
df['Rolegrouped'] = df['Role'].apply(lambda x: x if x in common_roles else 'Other')

# Encode target
le = LabelEncoder()
y = le.fit_transform(df['Rolegrouped'])

# Vectorize 'Key Skills'
tfidf = TfidfVectorizer(max_features=1320, stop_words='english')
skillstfidf = tfidf.fit_transform(df['Key Skills'])

# Prepare numeric features
df['min_exp'] = df['Job Experience Required'].str.extract(r'(\d+)').fillna(0).astype(float)  # example extraction
df['max_exp'] = df['Job Experience Required'].str.extract(r'-(\d+)').fillna(df['min_exp']).astype(float)
numeric_features = df[['min_exp', 'max_exp', 'sal']].fillna(0).values  # assuming 'sal' is salary column with no NaN
numeric_sparse = csr_matrix(numeric_features)

# Combine features
X = hstack([skillstfidf, numeric_sparse])

# Handle class imbalance by oversampling minority classes using SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

# Split train/test
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Train Random Forest classifier with balanced class weights
rf = RandomForestClassifier(class_weight='balanced', n_estimators=200, random_state=42)
rf.fit(X_train, y_train)

# Save model and objects for deployment
joblib.dump(rf, 'random_forest_model.pkl')
joblib.dump(tfidf, 'tfidf_vectorizer.pkl')
joblib.dump(le, 'label_encoder.pkl')

# Evaluate model
print("Train accuracy:", rf.score(X_train, y_train))
print("Test accuracy:", rf.score(X_test, y_test))

C:\Users\sanju\AppData\Local\Temp\ipykernel_16744\158368051.py:30: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['max_exp'] = df['Job Experience Required'].str.extract(r'-(\d+)').fillna(df['min_exp']).astype(float)

Train accuracy: 1.0
Test accuracy: 0.9583333333333334

In [48]:
import joblib
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.sparse import hstack, csr_matrix

# Save retrained model and preprocessing objects
joblib.dump(rf, 'random_forest_model.pkl')
joblib.dump(tfidf, 'tfidf_vectorizer.pkl')
joblib.dump(le, 'label_encoder.pkl')

# Load saved objects for prediction
tfidf_loaded = joblib.load('tfidf_vectorizer.pkl')
le_loaded = joblib.load('label_encoder.pkl')
rf_loaded = joblib.load('random_forest_model.pkl')

# Example prediction on new input
def predict_job_role(new_skills, min_exp, max_exp, salary):
    skills_tfidf = tfidf_loaded.transform([new_skills])
    numeric_features = np.array([[min_exp, max_exp, salary]])
    numeric_sparse = csr_matrix(numeric_features)
    X_new = hstack([skills_tfidf, numeric_sparse])
    
    pred_encoded = rf_loaded.predict(X_new)
    pred_label = le_loaded.inverse_transform(pred_encoded)
    return pred_label[0]

# Example usage
print(predict_job_role("python data analysis machine learning", 2.0, 5.0, 50000))

# Diagnostics on test set
y_test_pred = rf_loaded.predict(X_test)

print("Classification Report:")
print(classification_report(y_test, y_test_pred, target_names=le_loaded.classes_))

cm = confusion_matrix(y_test, y_test_pred)
plt.figure(figsize=(12,8))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=le_loaded.classes_, yticklabels=le_loaded.classes_, cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

Other
Classification Report:
                                            precision    recall  f1-score   support

             Accounts Executive/Accountant       1.00      0.98      0.99        56
Associate/Senior Associate -(NonTechnical)       0.96      0.98      0.97        47
   Associate/Senior Associate -(Technical)       0.98      1.00      0.99        61
                                     Other       0.83      0.88      0.85        60
                   Sales Executive/Officer       1.00      0.98      0.99        46
        Sales/Business Development Manager       0.94      0.97      0.95        60
                        Software Developer       0.98      0.90      0.94        69
                  Team Lead/Technical Lead       1.00      1.00      1.00        57

                                  accuracy                           0.96       456
                                 macro avg       0.96      0.96      0.96       456
                              weighted avg       0.96      0.96      0.96       456

In [ ]:
from flask import Flask, request, jsonify
import joblib
import numpy as np
from scipy.sparse import hstack, csr_matrix

# Load trained artifacts
rf_loaded = joblib.load('random_forest_model.pkl')
tfidf_loaded = joblib.load('tfidf_vectorizer.pkl')
le_loaded = joblib.load('label_encoder.pkl')

app = Flask(__name__)

@app.route('/predict', methods=['POST'])
def predict():
    # Expecting JSON with keys: skills, min_exp, max_exp, salary
    data = request.json
    skills = data.get('skills', '')
    min_exp = float(data.get('min_exp', 0))
    max_exp = float(data.get('max_exp', 0))
    salary = float(data.get('salary', 0))
    
    # Feature transformation
    skills_tfidf = tfidf_loaded.transform([skills])
    numeric_features = np.array([[min_exp, max_exp, salary]])
    numeric_sparse = csr_matrix(numeric_features)
    X_new = hstack([skills_tfidf, numeric_sparse])
    
    pred_encoded = rf_loaded.predict(X_new)
    pred_label = le_loaded.inverse_transform(pred_encoded)
    
    return jsonify({'predicted_role': str(pred_label[0])})

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.25.66.63:5000
Press CTRL+C to quit
127.0.0.1 - - [21/Sep/2025 02:34:10] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [21/Sep/2025 02:34:10] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [21/Sep/2025 02:34:14] "GET / HTTP/1.1" 404 -
10.25.66.63 - - [21/Sep/2025 02:34:44] "GET / HTTP/1.1" 404 -
10.25.66.63 - - [21/Sep/2025 02:34:44] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [21/Sep/2025 02:47:51] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:48:37] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:48:39] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:49:10] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:53:02] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:54:12] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:54:23] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:54:47] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:55:57] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:56:53] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:57:03] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:57:14] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:57:28] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:57:39] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 02:59:25] "POST /predict HTTP/1.1" 200 -

In [ ]:
from flask import Flask, request, jsonify
import joblib
import numpy as np
from scipy.sparse import hstack, csr_matrix

# Load trained artifacts
rf_loaded = joblib.load('random_forest_model.pkl')
tfidf_loaded = joblib.load('tfidf_vectorizer.pkl')
le_loaded = joblib.load('label_encoder.pkl')

app = Flask(__name__)

@app.route('/predict', methods=['POST'])
def predict():
    # Get JSON from request
    data = request.json
    skills = data.get('skills', '')
    min_exp = float(data.get('min_exp', 0))
    max_exp = float(data.get('max_exp', 0))
    salary = float(data.get('salary', 0))
    target_role = data.get('target_role', '').lower()  # target job role to screen for
    
    # Transform features
    skills_tfidf = tfidf_loaded.transform([skills])
    numeric_features = np.array([[min_exp, max_exp, salary]])
    numeric_sparse = csr_matrix(numeric_features)
    X_new = hstack([skills_tfidf, numeric_sparse])
    
    # Predict role
    pred_encoded = rf_loaded.predict(X_new)
    pred_label = le_loaded.inverse_transform(pred_encoded)[0]
    
    # Screening match boolean
    screened_in = (pred_label.lower() == target_role) if target_role else None
    
    # Return prediction and screening result
    return jsonify({'predicted_role': pred_label, 'screened_in': screened_in})

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.25.66.63:5000
Press CTRL+C to quit
127.0.0.1 - - [21/Sep/2025 11:11:57] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2025 11:13:51] "POST /predict HTTP/1.1" 200 -